var annotated_dup =
[
    [ "AboutDialog", "classAboutDialog.html", "classAboutDialog" ],
    [ "Application", "classApplication.html", "classApplication" ],
    [ "CoordinateXY", "structCoordinateXY.html", "structCoordinateXY" ],
    [ "DoubleSwitchDetector", "classDoubleSwitchDetector.html", "classDoubleSwitchDetector" ],
    [ "FileOpenDialog", "classFileOpenDialog.html", "classFileOpenDialog" ],
    [ "GeographicProjection", "structGeographicProjection.html", "structGeographicProjection" ],
    [ "GeometricTolerances", "structGeometricTolerances.html", "structGeometricTolerances" ],
    [ "GeometryUtils", "classGeometryUtils.html", "classGeometryUtils" ],
    [ "GeoParser", "classGeoParser.html", "classGeoParser" ],
    [ "GeoParsingTask", "classGeoParsingTask.html", "classGeoParsingTask" ],
    [ "GraphBuilder", "classGraphBuilder.html", "classGraphBuilder" ],
    [ "GraphBuildResult", "structGraphBuildResult.html", "structGraphBuildResult" ],
    [ "InvalidGeoJsonFormatException", "classInvalidGeoJsonFormatException.html", "classInvalidGeoJsonFormatException" ],
    [ "InvalidSwitchConfigException", "classInvalidSwitchConfigException.html", "classInvalidSwitchConfigException" ],
    [ "InvalidTopologyException", "classInvalidTopologyException.html", "classInvalidTopologyException" ],
    [ "LatLon", "structLatLon.html", "structLatLon" ],
    [ "Logger", "classLogger.html", "classLogger" ],
    [ "MainWindow", "classMainWindow.html", "classMainWindow" ],
    [ "NodeDegreeThresholds", "structNodeDegreeThresholds.html", "structNodeDegreeThresholds" ],
    [ "ParserDefaultValues", "structParserDefaultValues.html", "structParserDefaultValues" ],
    [ "ProgressBar", "classProgressBar.html", "classProgressBar" ],
    [ "RailwayParserException", "classRailwayParserException.html", "classRailwayParserException" ],
    [ "StraightBlock", "classStraightBlock.html", "classStraightBlock" ],
    [ "SwitchBlock", "classSwitchBlock.html", "classSwitchBlock" ],
    [ "SwitchOrientator", "classSwitchOrientator.html", "classSwitchOrientator" ],
    [ "TopologyEdge", "classTopologyEdge.html", "classTopologyEdge" ],
    [ "TopologyExtractor", "classTopologyExtractor.html", "classTopologyExtractor" ],
    [ "TopologyExtractResult", "structTopologyExtractResult.html", "structTopologyExtractResult" ],
    [ "TopologyGraph", "classTopologyGraph.html", "classTopologyGraph" ],
    [ "TopologySentinel", "structTopologySentinel.html", "structTopologySentinel" ],
    [ "WebViewPanel", "classWebViewPanel.html", "classWebViewPanel" ]
];