name: Build PR (CMake)

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Configure
      run: cmake -B build -G "Visual Studio 17 2022" -A x64

    - name: Build
      run: cmake --build build --config Release