name: Deploy Doxygen to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
    # -------------------------------------------------------------------------
    # Checkout
    # -------------------------------------------------------------------------
    - name: Checkout
      uses: actions/checkout@v4

    # -------------------------------------------------------------------------
    # Install Doxygen
    # -------------------------------------------------------------------------
    - name: Install Doxygen
      run: sudo apt-get update && sudo apt-get install doxygen graphviz -y

    # -------------------------------------------------------------------------
    # Generate docs
    # -------------------------------------------------------------------------
    - name: Generate docs
      run: doxygen Doxyfile

    # -------------------------------------------------------------------------
    # Deploy to gh-pages
    # -------------------------------------------------------------------------
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/doxygen/html